<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The Promise API</title>
</head>
<body>
    <script>
let p1 = new Promise((resolve, reject)=>{
    setTimeout(() => {
        resolve("value 1")
    }, 1000);
})
let p2 = new Promise((resolve, reject)=>{
    setTimeout(() => {
        // resolve("value 2")
        reject(new Error("error"))
    }, 2000);
})
let p3 = new Promise((resolve, reject)=>{
    setTimeout(() => {
        resolve("value 3")
    }, 3000);
})

p1.then((value)=>{console.log(value);})
p2.then((value)=>{console.log(value);})
p3.then((value)=>{console.log(value);})

// these all are waiting for all promises to resolve or reject 

// let promise_all = Promise.all([p1, p2, p3]);  // .all([p]) is function will work perfectly but if there is an error then this promise fail to return values

// promise.allsettled()
// let promise_all = Promise.allSettled([p1, p2, p3]) // it gives all promise results if one of them is rejected 

// promise.race()
// let promise_all = Promise.race([p1, p2, p3])  // gives value of promise which is firstly resolved but if error will win the race then promise is rejected

// promise.any()
// let promise_all = Promise.any([p1, p2, p3])   // waits for fullfill the promise with resolve value

// resolve()
// let promise_all = Promise.resolve(7)
let promise_all = Promise.reject(new Error("hi I am error"))
promise_all.then((value)=>{console.log(value);})
    </script>
</body>
</html>